spring.datasource.url=jdbc:postgresql://localhost:5432/fod
spring.datasource.username=postgres
spring.datasource.password=Luizant012!

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

api.security.token.secret=${JWT.SECRET:my-secret-key}